#!/bin/bash
# runUI-CONTAINERS.sh — bring up the Phase 3 local container stack (SAFE launcher).
#
# Why this wrapper instead of `docker compose up` directly:
#   1. DB SAFETY. The stack must hit ONLY the TEST Cloud SQL instance. This script
#      derives a git-ignored .env.docker (TEST connection name + credentials pulled
#      from QUANTCORE_TEST_DB_DSN) and runs `docker compose --env-file .env.docker`,
#      which SUPPRESSES Compose's default ./.env load — so the prod QUANTCORE_DB_DSN /
#      CLOUDSQL_CONNECTION_NAME in .env can never leak into the containers.
#   2. No secrets are hand-copied: the TEST password is read from the single source
#      of truth (QUANTCORE_TEST_DB_DSN in .env) at launch time.
#
# Usage:
#   ./runUI-CONTAINERS.sh up --build       # build images + start the stack (first run)
#   ./runUI-CONTAINERS.sh up -d            # start detached
#   ./runUI-CONTAINERS.sh down             # stop + remove
#   ./runUI-CONTAINERS.sh logs -f quantcore-api
#   ./runUI-CONTAINERS.sh ps
# Any args are passed straight through to `docker compose`.

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# --- TEST instance identity (NEVER the prod values in .env) ---
CLOUDSQL_INSTANCE="quantcore-test-20260606:us-central1:quantcore"
CLOUDSQL_QUOTA_PROJECT="quantcore-test-20260606"
GCLOUD_ADC="${GOOGLE_APPLICATION_CREDENTIALS:-$HOME/.config/gcloud/application_default_credentials.json}"

if [[ ! -f .env ]]; then
  echo "ERROR: .env not found (needed for QUANTCORE_TEST_DB_DSN)." >&2
  exit 1
fi
if [[ ! -f "$GCLOUD_ADC" ]]; then
  echo "ERROR: Google ADC not found at $GCLOUD_ADC" >&2
  echo "       Run:  gcloud auth application-default login" >&2
  exit 1
fi

# --- Parse the TEST DSN (postgresql://user:pass@host:port/db) — single source of truth ---
TEST_DSN="$(grep '^QUANTCORE_TEST_DB_DSN=' .env | cut -d= -f2-)"
if [[ -z "$TEST_DSN" ]]; then
  echo "ERROR: QUANTCORE_TEST_DB_DSN missing from .env." >&2
  exit 1
fi
DB_USER="$(printf '%s' "$TEST_DSN" | sed -E 's#^postgresql://([^:]+):.*#\1#')"
DB_PASS="$(printf '%s' "$TEST_DSN" | sed -E 's#^postgresql://[^:]+:([^@]+)@.*#\1#')"
DB_NAME="$(printf '%s' "$TEST_DSN" | sed -E 's#.*/([^/?]+)(\?.*)?$#\1#')"

# --- Write the git-ignored, TEST-only env file that drives compose substitution ---
cat > .env.docker <<EOF
# AUTO-GENERATED by runUI-CONTAINERS.sh — DO NOT EDIT, DO NOT COMMIT.
# Derived from QUANTCORE_TEST_DB_DSN. Points the local stack at the TEST instance only.
CLOUDSQL_INSTANCE=$CLOUDSQL_INSTANCE
CLOUDSQL_QUOTA_PROJECT=$CLOUDSQL_QUOTA_PROJECT
GCLOUD_ADC=$GCLOUD_ADC
QUANTCORE_DB_USER=$DB_USER
QUANTCORE_DB_PASSWORD=$DB_PASS
QUANTCORE_DB_NAME=$DB_NAME
EOF
chmod 600 .env.docker

echo "→ Stack targets TEST instance: $CLOUDSQL_INSTANCE (db=$DB_NAME user=$DB_USER)"
echo "→ docker compose --env-file .env.docker ${*:-up --build}"

exec docker compose --env-file .env.docker "${@:-up --build}"
